languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "time will talk..."

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  description = "散葉的个人博客站点"
  copyright = "© { year } 散葉 · 作者保留一切权力，禁止转载 · Free Palestine!&#127477;&#127480;"

[params.author]
  name = "散葉"
  image = "img/avatar_round.png"
  bio = "欢迎来到我的站点！"
  headline = "愿世界和平"
  links = [
    { github = "https://github.com/MoePunchQWQ" },
    { steam = "https://steamcommunity.com/profiles/890668584" },
    { mastodon = "https://hachyderm.io/@MoePunch"}
  ]